accounts/urls.py
app_name = "accounts"
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    # path(
    #     "toggle_favourite/<int:drink_id>/",
    #     views.toggle_favourite,
    #     name="toggle_favourite",
    # ),
    path("favourites/", views.favourites, name="favourites"),
    path("recent/", views.recent, name="recent"),
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    # path("create/", views.create, name="create"),
]

drinks/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", views.drink_list),  # List of all drinks
    path("api/<int:id>", views.drink_info),  # Individual drink
    path("api/random/", views.random_drinks),  # List of random drinks
    path("api/search/name", views.search_drink_name),  # Search for drinks by name
    path("api/search/ingredient", views.search_drink_ingredient),  # Search for drinks by ingredient
    path("", views.homepage, name="homepage"),
    path("account/", include("accounts.urls")),
    path("drinks/<int:id>", views.drink_detail, name="drink_detail"),
    path("drinks/", views.drinks, name="drinks"),
    # path("mocktails/<name>", views.mocktail_detail),
    path("account/create/", views.create, name="create"),
]

urlpatterns = format_suffix_patterns(urlpatterns)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# admin:password

drinks/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
import uuid


class Drink(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField(blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    unique_slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if (
            self.thumbnail == ""
            or self.thumbnail is None
            or self.thumbnail == "default.png"
        ):
            self.thumbnail = "default.png"
            # if not self.slug:  # Only set the slug when the object is first created.

            unique_suffix = uuid.uuid4().hex[:8]
            self.unique_slug = slugify(self.name) + "_" + unique_suffix
            self.slug = slugify(self.name)
            # self.slug = slugify(self.name)  # This will replace unwanted characters.
        super(Drink, self).save(*args, **kwargs)  # Call the "real" save() method.

    alcoholic = models.TextField(blank=True, null=True)
    type = models.TextField(blank=True, null=True)
    thumbnail = models.ImageField(
        default="default.png",
        upload_to="drink_images/",
        blank=True,
        null=True,
    )
    glass = models.TextField(blank=True, null=True)
    category = models.TextField(blank=True, null=True)
    ingredient1 = models.TextField(blank=True, null=True)
    ingredient2 = models.TextField(blank=True, null=True)
    ingredient3 = models.TextField(blank=True, null=True)
    ingredient4 = models.TextField(blank=True, null=True)
    ingredient5 = models.TextField(blank=True, null=True)
    ingredient6 = models.TextField(blank=True, null=True)
    ingredient7 = models.TextField(blank=True, null=True)
    ingredient8 = models.TextField(blank=True, null=True)
    ingredient9 = models.TextField(blank=True, null=True)
    measurement1 = models.TextField(blank=True, null=True)
    measurement2 = models.TextField(blank=True, null=True)
    measurement3 = models.TextField(blank=True, null=True)
    measurement4 = models.TextField(blank=True, null=True)
    measurement5 = models.TextField(blank=True, null=True)
    measurement6 = models.TextField(blank=True, null=True)
    measurement7 = models.TextField(blank=True, null=True)
    measurement8 = models.TextField(blank=True, null=True)
    measurement9 = models.TextField(blank=True, null=True)
    instructions = models.TextField(blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    class Meta:
        db_table = "drink"

drinks/forms.py
from django import forms
from . import models


class Create(forms.ModelForm):
    class Meta:
        model = models.Drink
        fields = [
            "name",
            "alcoholic",
            "type",
            "thumbnail",
            "glass",
            "category",
            "ingredient1",
            "ingredient2",
            "ingredient3",
            "ingredient4",
            "ingredient5",
            "ingredient6",
            "ingredient7",
            "ingredient8",
            "ingredient9",
            "measurement1",
            "measurement2",
            "measurement3",
            "measurement4",
            "measurement5",
            "measurement6",
            "measurement7",
            "measurement8",
            "instructions",
        ]

drinks/views.py
from django.http import JsonResponse
from django.http import HttpResponse
from .models import Drink
from accounts.models import Account
from .serializers import DrinkSerializer
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from . import forms
import requests
from django.conf import settings
from django.core.files.base import ContentFile
import uuid
import random
from PIL import Image
from django.contrib.postgres.search import SearchVector
import io
from rest_framework.pagination import PageNumberPagination


limitDisplay = 20 # Default number of drinks to display per page


@api_view(["GET", "POST"])
def drink_list(request, format=None):
    # get all drinks from the database
    # serialize them to json
    # return the json

    if request.method == "GET":
        drinks = Drink.objects.all()
        serializer = DrinkSerializer(drinks, many=True)
        return Response(serializer.data)

    if request.method == "POST":
        serializer = DrinkSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)


@api_view(["GET", "PUT", "DELETE"])
def drink_info(request, id, format=None):
    try:
        drink = Drink.objects.get(pk=id)
    except Drink.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == "GET":
        serializer = DrinkSerializer(drink)
        return Response(serializer.data)

    elif request.method == "PUT":
        serializer = DrinkSerializer(drink, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == "DELETE":
        drink.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


def homepage(request):
    return render(request, "homepage.html")


    
@api_view(["GET"])
def random_drinks(request):  # API function to get random drinks
    random = Drink.objects.order_by('?')
    limit = int(request.GET.get("limit", "")) # get the limit parameter from the request, no default
    start = int(request.GET.get("start", ""))
    queryset = random[start:start + limit]
    serializer = DrinkSerializer(queryset, many=True)
    return Response(serializer.data)



@api_view(["GET"])
def search_drink_name(request):
    search_query = request.GET.get("q", "")
    limit = int(request.GET.get("limit", "")) # get the limit parameter from the request, no default
    start = int(request.GET.get("start", ""))

    if search_query:
        drinks = Drink.objects.annotate(search=SearchVector('name')).filter(search=search_query)
    queryset = drinks[start:start + limit]
    serializer = DrinkSerializer(queryset, many=True)
    return Response(serializer.data)

@api_view(["GET"])
def search_drink_ingredient(request):
    search_query = request.GET.get("q", "")
    limit = int(request.GET.get("limit", "")) # get the limit parameter from the request, no default
    start = int(request.GET.get("start", ""))
    if search_query:
        drinks = Drink.objects.annotate(search=SearchVector
                                        ('ingredient1', 'ingredient2', 'ingredient3', 'ingredient4', 'ingredient5',
                                         'ingredient6', 'ingredient7', 'ingredient8', 'ingredient9'
                                         )).filter(search=search_query)
    queryset = drinks[start:start + limit]
    serializer = DrinkSerializer(queryset, many=True)
    return Response(serializer.data)


    

# def cocktails(request):
#     alcoholicDrinks = Drink.objects.filter(alcoholic="Alcoholic")
#     return render(request, "cocktails.html", {"drinks": alcoholicDrinks})


# def mocktails(request):
#     nonAlcoholicDrinks = Drink.objects.filter(alcoholic="Non alcoholic").order_by(
#         "name"
#     )
#     return render(request, "mocktails.html", {"drinks": nonAlcoholicDrinks})


def drinks(request):
    show_type = request.GET.get("show_alcoholic", "all")

    if request.user.is_authenticated:
        if show_type == "1":
            drinks = Drink.objects.filter(
                alcoholic="Alcoholic", author=None
            ) | Drink.objects.filter(alcoholic="Alcoholic", author=request.user)

        elif show_type == "0":
            drinks = Drink.objects.filter(
                alcoholic="Non alcoholic", author=None
            ) | Drink.objects.filter(alcoholic="Non alcoholic", author=request.user)

        else:
            drinks = Drink.objects.filter(author=None) | Drink.objects.filter(
                author=request.user
            )

    else:
        if show_type == "1":
            drinks = Drink.objects.filter(alcoholic="Alcoholic", author=None)
        elif show_type == "0":
            drinks = Drink.objects.filter(alcoholic="Non alcoholic", author=None)
        else:
            drinks = Drink.objects.filter(author=None)

    # Moved the return statement outside of the if-else blocks so it gets executed in all cases.
    return render(
        request,
        "drinks.html",
        {"drinks": drinks},
    )


# def drink_detail(request, id):
#     drink = Drink.objects.get(pk=id)

#     return render(request, "drinkDetail.html", {"drink": drink})


def drink_detail(request, id):
    drink = Drink.objects.get(pk=id)
    drink.save()  # Essencially a no-op, but it will call the save method and set the slug if it's not already set

    GPT_prompt = f"Create a photo-realistic image of an alcoholic drink presented in a clear {drink.glass}."
    GPT_prompt += f"The image should utilize a soft clay color palette, ensuring no parts of the drink resemble words or text - it is crucial."
    GPT_prompt += f"The drink should be elegantly simple, featuring specific ingredients listed in the drink's recipe: "

    if (
        (drink.thumbnail == "default.png")
        and drink.instructions
        and drink.author == None
        and drink.author == 1
    ):
        if drink.ingredient1 and drink.measurement1:
            GPT_prompt += f"{drink.ingredient1} adds a subtle hue to the liquid; "
        if drink.ingredient2 and drink.measurement2:
            GPT_prompt += f"{drink.ingredient2} which may alter the texture slightly;"
        if drink.ingredient3 and drink.measurement3:
            GPT_prompt += f"{drink.ingredient3}, "
        if drink.ingredient4 and drink.measurement4:
            GPT_prompt += f"{drink.ingredient4}, "
        if drink.ingredient5 and drink.measurement5:
            GPT_prompt += f"{drink.ingredient5}, "
        if drink.ingredient6 and drink.measurement6:
            GPT_prompt += f"{drink.ingredient6}, "
        if drink.ingredient7 and drink.measurement7:
            GPT_prompt += f"{drink.ingredient7}, "
        if drink.ingredient8 and drink.measurement8:
            GPT_prompt += f"{drink.ingredient8}, "
        if drink.ingredient9 and drink.measurement9:
            GPT_prompt += f"{drink.ingredient9} "
        GPT_prompt += (
            "each contributing to the overall aesthetic in a minimalistic way."
        )
        GPT_prompt += f"The {drink.glass} should be accurate and set against a neutral background to emphasize the drink itself"
        GPT_prompt += f"Pay particular attention to the garnishes as detailed in the instructions: {drink.instructions}."
        GPT_prompt += f"The focus should be on the clarity of the drink, the purity of the ice cubes,"
        GPT_prompt += f" and the overall sophistication of the presentation without any distractions."
        GPT_prompt += f"It is EXTREMELY important the image does NOT contain any text, writing, or logos."

        API_KEY = settings.OPENAI_API_KEY
        headers = {
            "Authorization": f"Bearer {API_KEY}",
            "Content-Type": "application/json",
        }
        data = {
            "model": "dall-e-3",
            "prompt": GPT_prompt,
            "n": 1,  # Number of images to generate
            "size": "1024x1024",  # Image size
            "quality": "standard",
        }

        # Make the API request to generate the image
        response = requests.post(
            "https://api.openai.com/v1/images/generations", headers=headers, json=data
        )

        # Check if the API request was successful
        if response.status_code == 200:
            response_data = response.json()
            image_url = response_data["data"][0]["url"]

            # Download the generated image
            image_response = requests.get(image_url)
            # Assuming 'image_response' contains the successful response from the image download request
            if image_response.status_code == 200:
                # Generate a unique suffix for the filename
                # unique_suffix = uuid.uuid4().hex[:8]
                # filename = f"{drink.slug}_{unique_suffix}.png"
                filename = f"{drink.unique_slug}.png"

                # Create a ContentFile object from the image content
                image_content = ContentFile(image_response.content, name=filename)

                # Save this content directly to the Drink object's thumbnail field
                drink.thumbnail.save(filename, image_content, save=True)

    # Prepare the context for rendering the template, including the drink and image details
    context = {
        "drink": drink,
        "GPT_prompt": GPT_prompt,
        "image_url": drink.thumbnail.url if drink.thumbnail else None,
    }
    # Render and return the drink detail page with the provided context
    return render(request, "drinkDetail.html", context)


@login_required(login_url="accounts:login")
def create(request):
    if request.method == "POST":
        form = forms.Create(request.POST, request.FILES)

templates/baseLayout.html
<!DOCTYPE html>
{% load static %} <!-- Load static files here -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    {% block head %}

    {% endblock %}
    <script src="{% static 'app.js' %}"></script> <!-- Load javascript file here -->
  </head>
  <body>
    <nav>
      <ul>
        <a href="{% url 'homepage' %}">Home</a>
        <a href="{% url 'drinks' %}">All Drinks</a>
        <a href="{% url 'accounts:recent' %}">Recent</a>
        <a href="{% url 'accounts:favourites' %}">Favourites</a>
        <div class="dropdown">
          <button class="dropbtn">Account</button>
          <div class="dropdown-content">
            <a href="{% url 'accounts:login' %}">Login</a>
            <a href="{% url 'accounts:register' %}">Register</a>
            <a href="{% url 'create' %}">Create new Drink</a>
            {% if user.is_authenticated %}
              <a>
                <form action="{% url 'accounts:logout' %}" method="post">
                  {% csrf_token %}
                  <input type="submit" value="Logout" />
                </form>
              </a>
            {% endif %}
          </div>
        </div>
      </ul>
    </nav>
    {% block content %}

    {% endblock %}
  </body>
</html>

templates/create.html
{% extends 'baseLayout.html' %}
{% load static %}

{% block head %}
  <title>Create a New Drink</title>
{% endblock %}

{% block content %}
  <div class="drink-detail-container">
    <h2>Create Your Own Drink</h2>
    <form class="form" action="{% url 'create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="drink-info">
        <label for="name">Drink Name:</label>
        <input type="text" id="name" name="name" placeholder="Enter drink name" required />
      </div>
      <div class="drink-detail-image">
        <label for="thumbnail">Drink Image:</label>
        <input type="file" id="thumbnail" name="thumbnail" accept="image/*" />
      </div>
      <div class="drink-info">
        <label for="alcoholic">Is it alcoholic?</label>
        <select id="alcoholic" name="alcoholic" required>
          <option value="Alcoholic">Alcoholic</option>
          <option value="Non alcoholic">Non Alcoholic</option>
        </select>
        <div class="glass-type">
          <label for="glass">Glass Type:</label>
          <input type="text" id="glass" name="glass" placeholder="Enter glass type" required />
        </div>
        <div class="instructions">
          <label for="instructions">Instructions:</label>
          <textarea id="instructions" name="instructions" rows="4" placeholder="Enter preparation instructions" required></textarea>
        </div>
      </div>

      <!-- Add input fields for ingredients and measurements as needed -->

      <div class="form-group">
        <button type="submit" class="button">Create Drink</button>
      </div>
    </form>
  </div>
{% endblock %}

templates/drinkDetail.html
{% extends 'baseLayout.html' %}
{% load static %}

{% block head %}
  <title>{{ drink.name }}</title>
{% endblock %}

{% block content %}
  <div class="drink-detail-container">
    <h3 class="drink-detail-title">Drink Detail</h3>
    <div class="drink-detail-image">
      {% if drink.thumbnail %}
        <img src="{{ drink.thumbnail.url }}" alt="{{ drink.name }}" />
      {% endif %}
    </div>
    <div class="drink-detail-name">{{ drink.name }}</div>

    <div class="drink-info">
      <div id="like-container">
        {% if drink.alcoholic == 'Alcoholic' %}
          <div class="alcoholic-indicator">Alcoholic</div>
        {% endif %}
        {% if drink.alcoholic == 'Non alcoholic' %}
          <div class="non-alcoholic-indicator">Non Alcoholic</div>
        {% endif %}
        <div id="drink-details"></div>
        <button id="like-button" class="like-button" data-drink-id="{{ drink.id }}">
          <span class="heart-icon"></span>
          <span class="like-text">Like</span>
        </button>
      </div>

      <div class="glass-type">Glass: {{ drink.glass }}</div>
      <div class="ingredients">
        <h3>Ingredients</h3>
        <ul>
          {% if drink.ingredient1 and drink.measurement1 %}
            <li>{{ drink.ingredient1 }} {{ drink.measurement1 }}</li>
          {% endif %}
          {% if drink.ingredient2 and drink.measurement2 %}
            <li>{{ drink.ingredient2 }} {{ drink.measurement2 }}</li>
          {% endif %}
          {% if drink.ingredient3 and drink.measurement3 %}
            <li>{{ drink.ingredient3 }} {{ drink.measurement3 }}</li>
          {% endif %}
          {% if drink.ingredient4 and drink.measurement4 %}
            <li>{{ drink.ingredient4 }} {{ drink.measurement4 }}</li>
          {% endif %}
          {% if drink.ingredient5 and drink.measurement5 %}
            <li>{{ drink.ingredient5 }} {{ drink.measurement5 }}</li>
          {% endif %}
          {% if drink.ingredient6 and drink.measurement6 %}
            <li>{{ drink.ingredient6 }} {{ drink.measurement6 }}</li>
          {% endif %}
          {% if drink.ingredient7 and drink.measurement7 %}
            <li>{{ drink.ingredient7 }} {{ drink.measurement7 }}</li>
          {% endif %}
          {% if drink.ingredient8 and drink.measurement8 %}
            <li>{{ drink.ingredient8 }} {{ drink.measurement8 }}</li>
          {% endif %}
          {% if drink.ingredient9 and drink.measurement9 %}
            <li>{{ drink.ingredient9 }} {{ drink.measurement9 }}</li>
          {% endif %}
        </ul>
      </div>
      <div class="instructions">
        <h3>Instructions</h3>
        <p>{{ drink.instructions }}</p>
      </div>
    </div>
  </div>
{% endblock %}

templates/drinks.html
{% extends 'baseLayout.html' %}
{% load static %}

{% block head %}
  <title>Cocktails</title>
{% endblock %}

{% block content %}
  <h1>Cocktails</h1>

  <div class="search-bar">
    <input type="text" id="search-input" placeholder="Search..." />
  </div>

  <div class="filter-options">
    <label for="filter-name">Search by:</label>
    <input type="radio" id="filter-name" name="filter" value="name" checked />
    <label for="filter-name">Name</label>
    <input type="radio" id="filter-ingredient" name="filter" value="ingredient" />
    <label for="filter-ingredient">Ingredient</label>
  </div>

  <div id="random-results" class="drinks-grid"></div>
{% endblock %}

templates/homepage.html
{% extends 'baseLayout.html' %}
{% load static %}

{% block head %}
  <title>Homepage</title>
{% endblock %}

{% block content %}
  <div class="center-vertical">
    <h1>Get drink recommendations!</h1>

    <form action="query.html" method="get" class="search-bar">
      <input type="text" name="search" placeholder="What type of drink are you feeling..." />
      <button type="submit"><img src="{% static 'search.png' %}" alt="Search" /></button>
    </form>

    <div class="image-container">
      <div>
        <a href="/drinks">
          <img src="{% static 'cocktail.png' %}" alt="Cocktails" class="round-image" />
          <p>Cocktails</p>
        </a>
      </div>

      <div>
        <a href="/mocktails">
          <img src="{% static 'mocktail.png' %}" alt="Mocktails" class="round-image" />
          <p>Mocktails</p>
        </a>
      </div>
    </div>
  </div>
{% endblock %}

templates/mocktails.html
<!DOCTYPE html>
<html>
<head>
    <title>Mocktails</title>
</head>
<body>
    <h1>Mocktails</h1>
        <div class="drinks">

        {% for drinks in drinks %}
            <div class="drinks">
                <h2><a href="#">{{ drinks.name }}</a></h2>
                <p>{{ drinks.description }}</p>
        {% endfor %}
        </div>
</body>
</html>